### ISSUE TITLE
Feature request: 'Mastery' / 'Apply Mastery / Level' to own skillset

### ISSUE THREAD

**Issue by manfred-ackermann** [osmium-org/osmium#193] opened 2017-06-29 18:12 UTC
I would like to propose a feature.

Problem:
I'd like to be able to see how the stats would be not only on both extremes of All 0 and V but also by applying the needed skills I'm missing at the moment.

Solution:
Showing a calculation based on applied ship mastery level 0 to 5 and or Module skill requirements not sufficient covered by own skill-set by extending the drop-down menu {username} in the Mastery section by

1. 'Apply Mastery' with another drop-down menu 'Level 0' to 'Level 5' and by
2. 'Apply Module' with another drop-down menu 'None', 'Minimum', 'At least III', "All V'

I'm happy to discuss or answer any question regarding this request.

Greetings,
 Manfred Ackermann

**Comment by Artefact2** [comment] 2017-06-30 09:28
Thanks for the suggestion. Duplicate of #28.

**Closed as completed by Artefact2** 2017-06-30 09:28 UTC
Labels: duplicate, enhancement
