### ISSUE TITLE
Too many modules: coloring & calculation

### ISSUE THREAD

**Issue by MarauderIIC** [osmium-org/osmium#97] opened 2015-04-11 20:06 UTC
There is some odd behavior when too many modules are added for a slot size.

Say that my medium slots take six modules. If I add a seventh module, it is colored red and is included in the calculations on the left side of the screen. Since it's colored red I wouldn't expect it to be included in the calculations.

When I move the red-colored module into the top six (or however many I have) slots, the bottom module is pushed down to the 7th slot and is colored red, as expected. However, the module I dragged up to the top six is also colored red. In this way it is possible to get many, if not all, modules for a slot size to be colored red. I would expect it to be recolored to white since it is in the range of slots that are included in the calculations.

**Comment by Artefact2** [comment] 2015-04-11 20:59
> Say that my medium slots take six modules. If I add a seventh module, it is colored red and is included in the calculations on the left side of the screen. Since it's colored red I wouldn't expect it to be included in the calculations.

It's a feature, not a bug. This approach is more future-proof (and also past-proof). If the number of slots on a ship were to change, you would be able to see what its stats will be (or were) with the new (or old) slot counts.

If you don't want to include any module in the calculations, offline it.

> When I move the red-colored module into the top six (or however many I have) slots, the bottom module is pushed down to the 7th slot and is colored red, as expected. However, the module I dragged up to the top six is also colored red. In this way it is possible to get many, if not all, modules for a slot size to be colored red. I would expect it to be recolored to white since it is in the range of slots that are included in the calculations.

That is a bug. Thanks for reporting!

**Comment by Artefact2** [comment] 2015-05-08 21:36
Fixed in 7c61830.

**Closed by Artefact2** 2015-05-08 21:36 UTC
Labels: bug
