### ISSUE TITLE
Feedback panel is in the way of fitting panel.

### ISSUE THREAD

**Issue by Caldfir** [osmium-org/osmium#114] opened 2015-10-24 16:32 UTC
The "feedback" panel gets in the way of the "browse fittings" section.  I'm not sure where you could put it to be less obtrusive - maybe don't have it as a tab at all - just add "feedback" to the header bar?  

Dunno... it is aggravating to keep clicking the thing by accident though.

**Comment by Artefact2** [comment] 2015-12-09 13:40
Duplicate of #105.

**Closed as completed by Artefact2** 2015-12-09 13:40 UTC
Labels: bug, duplicate
