### ISSUE TITLE
There doesn't seem to be a way to select a ship.

### ISSUE THREAD

**Issue by RheaAyase** [osmium-org/osmium#161] opened 2016-07-17 17:27 UTC
1. `Create Loadout` points me to `https://o.smium.org/new/:id`
2. I am greeted by `No ship selected.` label, while there is no obvious way to select a ship. The user interface is just useless at displaying it - the user should not have to search for ship under the "browse" but instead should be navigated through ship selection in the first place, before being able to see any of the "fitting" stuff.
   ([screenshot](http://my.jetscreenshot.com/11695/20160717-mld7-286kb.png))

Browser - chrome.

**Comment by Artefact2** [comment] 2016-07-17 18:35
Thanks for reporting, but this is a duplicate of #137.

**Closed as completed by Artefact2** 2016-07-17 18:35 UTC
Labels: enhancement
