### ISSUE TITLE
Improve database search (search by module slot)

### ISSUE THREAD

**Issue by RheaAyase** [osmium-org/osmium#162] opened 2016-07-17 17:32 UTC
Improve database search by allowing the user to search for modules by selecting where do they want to equip them.

Example: A newbie like myself does not know what modules exist, and therefor would like to see the full list of modules they can equip in a slot that they have empty.

**Comment by Artefact2** [comment] 2016-07-17 18:36
Duplicate of #57.

**Closed as completed by Artefact2** 2016-07-17 18:36 UTC
Labels: enhancement
