### ISSUE TITLE
Add default "sharing option" in settings

### ISSUE THREAD

**Issue by Cubox-** [osmium-org/osmium#66] opened 2014-09-20 11:43 UTC
My use of osmium is purely personnal. I won't share a fitting to the public, or very rarely.

I would love to be able to select default sharing settings in the settings, so I don't have to select through a list that my fit is private. Same for who can edit it and seen by.

**Comment by Artefact2** [comment] 2016-07-17 19:19
Duplicate of #53.

**Closed by Artefact2** 2016-07-17 19:19 UTC
Labels: enhancement
